service: sls-ts

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

package:
  individually: true

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 1
  webpack:
    packager: npm
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

provider:
  name: aws
  region: ${opt:region}
  runtime: nodejs14.x

functions:
  myFunction:
    name: myFunction-${opt:stage}
    handler: src/myFunction.handler
    package:
      individually: true
      patterns:
        - '!src/**'
        - 'src/myFunction.ts'
    tags:
      stage: ${opt:stage}
